from vetor_ordenado import VetorOrdenado

vetor = VetorOrdenado(10)
vetor.imprimir()
vetor.inserir(6)
vetor.inserir(4)
vetor.inserir(3)
vetor.inserir(5)
vetor.inserir(1)
vetor.inserir(8)
vetor.imprimir()
print(vetor.pesquisar(12))
print(vetor.pesquisar(6))
print(vetor.pesquisar(2))
print(vetor.pesquisar(4))
vetor.excluir(4)
print(vetor.pesquisar(4))
vetor.imprimir()
print(vetor.pesquisa_binaria(5))
print(vetor.pesquisa_binaria(8))
print(vetor.pesquisa_binaria(12))
